### ISSUE TITLE
Update to  alpha version of rust

### ISSUE THREAD

**Issue by raphaeljlps** [mattnenterprise/rust-ftp#1]
Could you update to at least the version alpha of Rust, please? (I tried to build with the nightly version   launched after the alpha release but couldn't) 
I tried to fix the errors myself but I'm still to new to rust, thanks.

**Comment by mattnenterprise** [comment]
Thanks for the issue. I will try and get it fixed today.

**Comment by raphaeljlps** [comment]
thank you! ;D

**Comment by mattnenterprise** [comment]
@raphaeljlps I have gotten this to compile. My library is still considered unstable because the networking module of the standard library is unstable. The example still works correctly for me. If you have any more problems let me know and I will fix it, or create a pull request. Pull requests are always welcome.

**Comment by raphaeljlps** [comment]
thanks @mattnenterprise sure I will make a PR when I can! ;D
