### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by mattnenterprise** [mattnenterprise/rust-ftp#27]
Some type of testing is needed to ensure the code still works when changes are made. We can test against a pure-ftpd server.

**Comment by matt2xu** [comment]
:+1: on this! I just realized my change to the pasv() method has a bug, which went unnoticed as the tests did not try to upload a file. I will update the test to check for that and fix the bug, and make a pull request. Sorry for that :disappointed:

**Comment by mattnenterprise** [comment]
It's ok. I wanted to get testing in before the next release to make sure all of the changes worked correctly. Thanks for doing this one.

**Comment by matt2xu** [comment]
Ok I wrote a simple test (based on the connecting.rs example). I'll make a pull request once #32 and #33 are merged to avoid conflicts. And then I'll rebase #30 on top of this to add the "put" method and test it.

**Comment by mattnenterprise** [comment]
@matt2xu I have been looking more at testing to make sure everything is working correctly. I have been wondering if it would be better to testing using a mockable DataStream, but then we would have problems with the pasv data connection stuff. Maybe we should start with creating a server using https://github.com/giampaolo/pyftpdlib. Then to test we run a bash script that starts the FTP server, runs the tests, and then shuts down the FTP server. What do you think ?

**Comment by matt2xu** [comment]
@mattnenterprise we already have some limited testing going on with Travis using pure-ftpd. However, this means that you have to wait for Travis to test when pushing to GitHub, or that you need to install pure-ftp with the same configuration as is in the .travis.yml file

I propose another solution. I have written a Dockerfile that configures a vsftpd server that we can use for testing what we want. See here: https://github.com/matt2xu/rust-ftp/tree/tests
I chose vsftpd because I couldn't figure out how to configure pure-ftpd, I find their documentation to be very poor.

Next step: update .travis.yml from the Dockerfile, make more complete tests, remove any "ignore" labels from tests.

**Comment by mattnenterprise** [comment]
Ok sounds great. 

We should also add some section to the README about setting up a dev environment for working on this project. I believe the only two things needed will be rust and docker.

**Comment by mattnenterprise** [comment]
The initial work for this has been completed.
